apiVersion: v1
kind: Service
metadata:
  name: medusa-app-service
spec:
  type: NodePort
  selector:
    app: medusa
  ports:
  - port: 3334
    targetPort: 3334
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: medusa-db-service
spec:
  type: ClusterIP
  selector:
    app: medusa-db
  ports:
  - port: 5432
    targetPort: 5432
